// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://naphgqjkgriezjkheqdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hcGhncWprZ3JpZXpqa2hlcWR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTc2NDcsImV4cCI6MjA2NzczMzY0N30.V5wiZ1To4yHxvsD-58tInrAk-ZylI3LZZNz9BBcIZqQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});